AdageSmartContent/AdageSmartContent.Epi.Web/Controllers/Adage.EpiStarterKit.ControllerPartials/LibraryPartials/Pages/SiteSettingsPageController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Adage.EpiStarterKit.ControllerPartials.Base;
using Adage.EpiStarterKit.ModelPartials.BusObj;
using Adage.EpiStarterKit.ModelPartials.Models.Pages;
using Adage.EpiStarterKit.ViewModelPartials.ViewModels;
using Adage.EpiStarterKit.ViewModelPartials.BusObj;
using EPiServer;
using EPiServer.Core;
using EPiServer.Framework.DataAnnotations;
using EPiServer.Web.Mvc;

namespace Adage.EpiStarterKit.ControllerPartials.Pages
{
    [TemplateDescriptor(ModelType = typeof(SiteSettingsPage))]
    public partial class SiteSettingsPageController : AdageBasePageController<SiteSettingsPage>
    {


        protected virtual string AdageViewsSharedRoot { get; } = "~/Views/AdageViews/Shared";
        protected virtual string ClientViewsSharedRoot { get; } = "~/Views/ClientViews/Shared";

        protected readonly IBreadcrumbService BreadcrumbService;
        protected readonly ISiteDataRepository SiteDataRepository;
        protected readonly ISiteNavigationRepository SiteNavigationRepository;

        public SiteSettingsPageController(ISiteDataRepository siteDataRepository, ISiteNavigationRepository siteNavigationRepository, IViewModelFactory viewModelFactory, IBreadcrumbService breadcrumbService)
            : base(viewModelFactory)
        {
            SiteDataRepository = siteDataRepository;
            SiteNavigationRepository = siteNavigationRepository;
            BreadcrumbService = breadcrumbService;
        }

        public ActionResult RenderBreadcrumbs(PageData currentPage)
        {
            string breadcrumbsViewName = "Breadcrumbs.cshtml";
            var breadcrumbList = BreadcrumbService.GetPageBreadcrumbs(currentPage);
            return GetViewForFile(breadcrumbsViewName, breadcrumbList);
        }

        public ActionResult RenderMegaNav()
        {
            string megaNavFileName = "MegaNav.cshtml";
            return GetViewForFile(megaNavFileName, SiteNavigationRepository);
        }

        public ActionResult RenderMegaNavMobile()
        {
            string megaNavFileName = "MegaNavMobile.cshtml";
            return GetViewForFile(megaNavFileName, SiteNavigationRepository);
        }

        public ActionResult RenderSearch()
        {
            string searchBarFileName = "SearchBar.cshtml";
            return GetViewForFile(searchBarFileName, SiteDataRepository);

        }

        public ActionResult RenderSearchMobile()
        {
            string searchBarMobileFileName = "SearchBarMobile.cshtml";
            return GetViewForFile(searchBarMobileFileName, SiteDataRepository);
        }

        private ActionResult GetViewForFile(string fileName, object model)
        {
            string clientViewLocation = $"{ClientViewsSharedRoot}/{fileName}";
            string adageViewLocation = $"{AdageViewsSharedRoot}/{fileName}";

            if (System.IO.File.Exists(Server.MapPath(clientViewLocation)))
            {
                return View(clientViewLocation, model);
            }
            else
            {
                return View(adageViewLocation, model);
            }
        }
    }
}

AdageSmartContent/AdageSmartContent.Epi.Web/Views/AdageViews/Shared/AccordionItem.cshtml
@using EPiServer.Core
@using EPiServer.Web.Mvc.Html
@using EPiServer.Framework.Web.Mvc.Html
@using Adage.EpiStarterKit.ModelPartials.Models.Pages
@using Adage.EpiStarterKit.ViewModelPartials.ViewModels.Pages
@using Adage.EpiStarterKit.ModelPartials.BusObj.NavigationObjects
@using Adage.EpiStarterKit.ViewModelPartials.Pocos

@model AccordionViewItem

<li class="adage-accordion-item">
    @if (EPiServer.Editor.PageEditing.PageIsInEditMode)
    {
        <p class="adage-accordion-trigger" data-epi-property-name="Title">
            @Model.Title
        </p>
    }
    else
    {
        <button class="adage-accordion-trigger" type="button" aria-controls="@Model.ClientID">
            @Model.Title
        </button>
    }

    <div class="adage-accordion-panel" aria-hidden="true" id="@Model.ClientID">
        <div class="adage-accordion-panel-content rich-text" data-accordion-content-id="@Model.ClientID" data-epi-property-name="AccordionContent">
            @Html.PropertyFor(m => Model.Content)
        </div>
    </div>
</li>

AdageSmartContent/AdageSmartContent.Epi.Web/Views/AdageViews/Shared/Breadcrumbs.cshtml
@using EPiServer.Core
@using EPiServer.Web.Mvc.Html
@using EPiServer.Framework.Web.Mvc.Html
@using Adage.EpiStarterKit.ModelPartials.Models.Pages
@using Adage.EpiStarterKit.ViewModelPartials.ViewModels.Pages
@using Adage.EpiStarterKit.ModelPartials.BusObj.NavigationObjects

@model List<LinkItem>

@if (Model != null)
{
    for (int i = 0; i < Model.Count; i++)
    {
        if (i != Model.Count - 1)
        {
            if (Model[i].Active)
            {
                <a class="" href="@Model[i].Href" title="@Model[i].Title">@Model[i].LinkText</a><span> > </span>
            }
            else
            {
                <span>@Model[i].LinkText > </span>
            }
        }
        else
        {
            <span>@Model[i].LinkText</span>
        }
    }

}

AdageSmartContent/AdageSmartContent.Epi.Web/Views/AdageViews/Shared/Footer.cshtml
@using EPiServer.Web.Mvc.Html
@using Adage.EpiStarterKit.ModelPartials.Models.Pages
@using Adage.EpiStarterKit.ViewModelPartials.ViewModels.Pages

@model IPageViewModel<AdageBasePage>

<footer class="page-footer">
    @*<section class="page-footer-inner footer-top">
        <div class="footer-top-inner">
            <ul class="adage-accordion-inner open-accordion" data-accordion-list="@Model.CurrentPage.WorkPageID" aria-label="Accordion Control Group Buttons">*@
                @*@if (!String.IsNullOrWhiteSpace(Model.SiteDataRepository.SiteSettingsPage.LeftWYSIWYGTitle) && Model.SiteDataRepository.SiteSettingsPage.LeftWYSIWYG != null)
                {
                    <li class="adage-accordion-item footer-block">
                        <button class="adage-accordion-trigger" type="button" aria-controls="LeftWYSIWYG" aria-expanded="false" data-epi-property-name="Title">
                            <h2 class="footer-top-title">@Model.SiteDataRepository.SiteSettingsPage.LeftWYSIWYGTitle</h2>
                        </button>
                        <div class="adage-accordion-panel" aria-hidden="true" id="LeftWYSIWYG">
                            <div class="adage-accordion-panel-content rich-text" data-accordion-content-id="LeftWYSIWYG" data-epi-property-name="AccordionContent">
                                @Html.PropertyFor(m => m.SiteDataRepository.SiteSettingsPage.LeftWYSIWYG)
                            </div>
                        </div>
                    </li>
                }*@
                @*@if (!String.IsNullOrWhiteSpace(Model.SiteDataRepository.SiteSettingsPage.LeftCenterWYSIWYGTitle) && Model.SiteDataRepository.SiteSettingsPage.LeftCenterWYSIWYG != null)
                {
                    <li class="adage-accordion-item footer-block">
                        <button class="adage-accordion-trigger" type="button" aria-controls="LeftCenterWYSIWYG" aria-expanded="false" data-epi-property-name="Title">
                            <h2 class="footer-top-title">@Model.SiteDataRepository.SiteSettingsPage.LeftCenterWYSIWYGTitle</h2>
                        </button>
                        <div class="adage-accordion-panel" aria-hidden="true" id="LeftCenterWYSIWYG">
                            <div class="adage-accordion-panel-content rich-text" data-accordion-content-id="LeftCenterWYSIWYG" data-epi-property-name="AccordionContent">
                                @Html.PropertyFor(m => m.SiteDataRepository.SiteSettingsPage.LeftCenterWYSIWYG)
                            </div>
                        </div>
                    </li>
                }*@
                @*@if (!String.IsNullOrWhiteSpace(Model.SiteDataRepository.SiteSettingsPage.RightCenterWYSIWYGTitle) && Model.SiteDataRepository.SiteSettingsPage.RightCenterWYSIWYG != null)
                {
                    <li class="adage-accordion-item footer-block">
                        <button class="adage-accordion-trigger" type="button" aria-controls="RightCenterWYSIWYGTitle" aria-expanded="false" data-epi-property-name="Title">
                            <h2 class="footer-top-title">@Model.SiteDataRepository.SiteSettingsPage.RightCenterWYSIWYGTitle</h2>
                        </button>
                        <div class="adage-accordion-panel" aria-hidden="true" id="RightCenterWYSIWYGTitle">
                            <div class="adage-accordion-panel-content rich-text" data-accordion-content-id="RightCenterWYSIWYGTitle" data-epi-property-name="AccordionContent">
                                @Html.PropertyFor(m => m.SiteDataRepository.SiteSettingsPage.RightCenterWYSIWYG)
                            </div>
                        </div>
                    </li>
                }*@
                @*@if (Model.SiteDataRepository.SiteSettingsPage.InstagramUrl != null)
                {
                    <li>
                        <a href="@Model.SiteDataRepository.SiteSettingsPage.InstagramUrl">
                            <svg class="svg-icon" aria-hidden="true" focusable="false">
                                <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-instagram" />
                            </svg>
                            <span class="visually-hidden">Instagram</span>
                        </a>
                    </li>
                }
            </ul>
        </div>

    </section>*@
    <section class="page-footer-inner footer-bottom">
        <div class="footer-bottom-inner">
            <div class="copyright">
                @if (!String.IsNullOrWhiteSpace(Model.SiteDataRepository.SiteSettingsPage.CopyrightText))
                {
                    <p @Html.EditAttributes(m => m.SiteDataRepository.SiteSettingsPage.CopyrightText)>&copy; @Model.SiteDataRepository.SiteSettingsPage.CopyrightText</p>
                }
            </div>
            <div class="user-info-links">
                @Html.PropertyFor(m => m.SiteDataRepository.SiteSettingsPage.FooterLinkArea)
            </div>
        </div>
    </section>
</footer>

AdageSmartContent/AdageSmartContent.Epi.Web/Views/AdageViews/Shared/Header.cshtml
@using EPiServer.Core
@using EPiServer.Core
@using EPiServer.Web.Mvc.Html
@using EPiServer.Framework.Web.Mvc.Html
@using Adage.EpiStarterKit.ModelPartials.Models.Pages
@using Adage.EpiStarterKit.ViewModelPartials.ViewModels.Pages

@model IPageViewModel<AdageBasePage>

<header id="siteHeader" class="header" role="banner">
    <div class="header-top">
        <div class="header-top-inner">
            <a href="/" class="header-logo">
                <img class="header-logo-image" src="@Url.ContentUrl(Model.SiteDataRepository.SiteSettingsPage.Logo.Image)" aria-hidden="true" role="presentation" />
                <span class="visually-hidden">Navigate to ATAP homepage</span>
            </a>

            <div class="mobile-nav">
                <button type="button" class="mobile-nav-search-trigger mobile-nav-search-trigger-js">
                    <svg class="svg-icon icon-search" aria-hidden="true" role="presentation" focusable="false">
                        <use xlink:href="#icon-search"></use>
                    </svg>
                    <span class="visually-hidden">Activate for site search</span>
                </button>

                <button type="button" class="mobile-nav-trigger mobile-nav-trigger-js" title="Activate for site menu" aria-label="Activate for site menu">
                    <span class="mobile-nav-trigger-icon" aria-hidden="true" role="presentation"><span></span></span>
                </button>
            </div>
        </div>
    </div>

    <div class="header-nav-container">
        <div class="header-nav">
            <div class="header-nav-inner">
                @{ Html.RenderAction("RenderMegaNav", "SiteSettingsPage"); }

                <div class="header-nav-secondary">
                    <div class="header-nav-secondary-inner">
                        @if (Model.SiteDataRepository.SiteSettingsPage.UtilityNavLinks != null)
                        {
                            <nav>
                                <ul>
                                    @foreach (var item in Model.SiteDataRepository.SiteSettingsPage.UtilityNavLinks)
                                    {
                                        <li><a href="@Url.ContentUrl(item.Href)">@item.Text</a></li>
                                    }
                                </ul>
                            </nav>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

AdageSmartContent/AdageSmartContent.Epi.Web/Views/AdageViews/Shared/HeaderMobile.cshtml
@using EPiServer.Core
@using EPiServer.Web.Mvc.Html
@using EPiServer.Framework.Web.Mvc.Html
@using Adage.EpiStarterKit.ModelPartials.Models.Pages
@using Adage.EpiStarterKit.ViewModelPartials.ViewModels.Pages

@model IPageViewModel<PageData>


<div class="header-nav">
    <a href="/">
        <img class="header-nav-logo" src="@Url.ContentUrl(Model.SiteDataRepository.SiteSettingsPage.Logo.Image)" />
    </a>
    <p>
        Mobile Nav
    </p>
    @{ Html.RenderAction("RenderMegaNavMobile", "SiteSettingsPage"); }
    @{ Html.RenderAction("RenderSearchMobile", "SiteSettingsPage"); }
</div>

AdageSmartContent/AdageSmartContent.Epi.Web/Views/AdageViews/Shared/MegaNav.cshtml
@using EPiServer.Core
@using EPiServer.Web.Mvc.Html
@using Adage.EpiStarterKit.ModelPartials.BusObj

@model ISiteNavigationRepository

<div id="siteNav" class="header-nav-primary">
    <nav class="nav">
        @if (Model.MegaNavItems != null)
        {
            <ul>
                @foreach (var navItem in Model.MegaNavItems)
                {
                    <li>
                        <a href="@navItem.NavPageData.LinkURL">
                            @navItem.NavPageData.Name
                        </a>
                    </li>
                }
            </ul>
        }
    </nav>
</div>

AdageSmartContent/AdageSmartContent.Epi.Web/Views/AdageViews/Shared/MegaNavMobile.cshtml
@using EPiServer.Core
@using EPiServer.Web.Mvc.Html
@using Adage.EpiStarterKit.ModelPartials.BusObj

@model ISiteNavigationRepository

<nav class="nav">
    @foreach(var linkItem in Model.UtilityNavLinks)
    {
        <a href="@Url.PageUrl(linkItem.Href)" target="@linkItem.Target" title="@linkItem.Title">@linkItem.LinkText</a>
    }
    @foreach (var navItem in Model.MegaNavItems)
    {
        if (navItem.IsMegaNavContainerPage)
        {
            <p>@navItem.NavPageData.Name</p>
            <div>
                @foreach (var childPage in navItem.MegaNavChildren)
                {
                    <p style="padding-left:1em">
                        <a href="@childPage.LinkURL">@childPage.Name</a>
                    </p>
                }
            </div>
        }
        else
        {
            <p>
                <a href="@navItem.NavPageData.LinkURL">@navItem.NavPageData.Name</a>
            </p>
        }
    }
</nav>

AdageSmartContent/AdageSmartContent.Epi.Web/Views/AdageViews/Shared/SearchBar.cshtml
@using EPiServer.Core
@using EPiServer.Web.Mvc.Html
@using Adage.EpiStarterKit.ModelPartials.BusObj

@model ISiteDataRepository

<div class="header-search">
    <div class="header-search-inner">
        <form action="@Model.SiteSettingsPage.SearchResultsPage" method="get">
            <label for="headerSearchField">Search through the site content</label>
            <div class="form-group">
                <input id="headerSearchField" type="search" name="q" placeholder="@Model.SiteSettingsPage.SearchPlaceholderText" required />
                <div class="form-group-btn">
                    <button type="submit" class="btn btn-primary">
                        <svg class="svg-icon icon-search" aria-hidden="true" role="presentation" focusable="false">
                            <use xlink:href="#icon-search"></use>
                        </svg>
                        <span class="visually-hidden">@Model.SiteSettingsPage.SearchButtonText</span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>

AdageSmartContent/AdageSmartContent.Epi.Web/Views/AdageViews/Shared/SearchBarMobile.cshtml
@using EPiServer.Core
@using EPiServer.Web.Mvc.Html
@using Adage.EpiStarterKit.ModelPartials.BusObj

@model ISiteDataRepository

<form action="@Model.SiteSettingsPage.SearchResultsPage" method="get">
    <input type="search" placeholder="@Model.SiteSettingsPage.SearchPlaceholderText" required />
    <input type="submit" value="@Model.SiteSettingsPage.SearchButtonText" />
</form>

AdageSmartContent/AdageSmartContent.Epi.Web/Views/AdageViews/Shared/StaffInfoItem.cshtml
@using EPiServer.Core
@using EPiServer.Web.Mvc.Html
@using Adage.EpiStarterKit.ModelPartials.Models.Blocks
@using Adage.EpiStarterKit.ViewModelPartials.ViewModels.Blocks
@using Adage.EpiStarterKit.ViewModelPartials.Pocos

@model StaffInfoViewItem

<article class="adage-staff-item">
    @if (!Model.HideImage)
    {
        <div class="adage-staff-item-img">
            @Html.PropertyFor(m => m.StaffImage)
        </div>
    }
    <div class="adage-staff-item-content">
        <h3 class="adage-staff-item-title">
            @Html.PropertyFor(m => m.StaffName)
        </h3>
        <h4 class="adage-staff-item-role">
            @Html.PropertyFor(m => m.StaffRole)
        </h4>
        <div class="rich-text adage-staff-item-info">
            @Html.PropertyFor(m => m.StaffInfo)
        </div>
    </div>
</article>